### ISSUE TITLE
Failed to activate the irc package

### ISSUE THREAD

**Issue by ThaFridge** [cjsaylor/atom-irc#34] opened 2017-09-13 14:31 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [irc](https://github.com/cjsaylor/atom-irc) package 0.4.0

### Stack Trace

Failed to activate the irc package

```
At The super constructor to "inherits" must not be null or undefined

TypeError: The super constructor to "inherits" must not be null or undefined
    at Object.exports.inherits (util.js:961:11)
    at /packages/irc/node_modules/irc/lib/irc.js:575:6)
    at /packages/irc/node_modules/irc/lib/irc.js:956:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/irc/lib/connector.coffee:2:7)
    at /packages/irc/lib/connector.coffee:1:1)
    at /packages/irc/lib/connector.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/irc/lib/irc.coffee:5:10)
    at /packages/irc/lib/irc.coffee:1:1)
    at /packages/irc/lib/irc.coffee:1:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:645:40)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -0:32.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
apex-syntax 0.2.0 
apex-ui 1.0.1 
atom-beautify 0.30.5 
atom-bootstrap3 1.2.12 
atom-clock 0.1.15 
autoclose-html 0.23.0 
ftp-remote-edit 0.12.1 
git-control 0.9.0 
highlight-selected 0.13.1 
irc 0.4.0 
local-history 4.3.0 
minimap 4.29.6 
open-on-bitbucket 0.5.0 
pigments 0.40.2 
pristine-ui 1.1.8 
pure-syntax 0.3.0 
```

**Comment by HebaruSan** [comment] 2017-09-14 10:14
This is a duplicate of #33.

**Comment by cjsaylor** [comment] 2017-09-14 15:47
Closing as @HebaruSan indicated is a dupe of #33.

**Closed as completed by cjsaylor** 2017-09-14 15:47 UTC
